version: 2.1
jobs: 
  build: 
    machine:
      image: ubuntu-2004:202104-01
    
    steps: 
      - checkout # check out the code in the project directory

      - run: | 
          sudo apt update 
          sudo apt install aria2
          npm i -g ipfs-store
      - run: 
          command: |
            mkdir vid
            cd vid
            aria2c --seed-time=2.0 "magnet:?xt=urn:btih:1FA043369B43F7AD3510BD3ACE46482B47A1AE90&dn=The.Ice.Road.2021.2160p.AMZN.WEB-DL.DDP5.1.HDR.HEVC-CMRG%5BTGx%5D+%E2%AD%90&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ffasttracker.foreverpirates.co%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fexplodie.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.cyberia.is%3A6969%2Fannounce&tr=udp%3A%2F%2Fipv4.tracker.harry.lu%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.uw0.xyz%3A6969%2Fannounce&tr=udp%3A%2F%2Fopentracker.i2p.rocks%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.birkenwald.de%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Ftracker.moeking.me%3A6969%2Fannounce&tr=udp%3A%2F%2Fopentor.org%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.dler.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce"
          no_output_timeout: 3h
      
      - run:
          command: |
            ipfs-store --apiKey "${NFT_API_KEY}" --path "./vid"
          no_output_timeout: 3h
