version: 2.1
jobs: 
  build: 
    machine:
      image: ubuntu-2004:202104-01
    
    steps: 
      - checkout # check out the code in the project directory

      - run: | 
          sudo apt update 
          sudo apt install aria2
          npm i -g ipfs-store ipfs-car
      - run: 
          command: |
            mkdir vid
            cd vid
            aria2c --seed-time=2.0 --file-allocation=none "magnet:?xt=urn:btih:6799249B510E811C1893E7ACB691AC3991040EFA&dn=The.Tomorrow.War.2021.1080p.WEBRip.x264-RARBG&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2720%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2890%2Fannounce&tr=udp%3A%2F%2Ftracker.thinelephant.org%3A12760%2Fannounce&tr=udp%3A%2F%2Ftracker.fatkhoala.org%3A13710%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce"
          no_output_timeout: 3h
      
      - run:
          command: |
            ipfs-car --pack ./vid
            ipfs-store --apiKey "${NFT_API_KEY}" --path "./vid"
          no_output_timeout: 3h
