version: 2.1
jobs: 
  build: 
    machine:
      image: ubuntu-2004:202104-01 
    environment:
      START: 701  
      END: 750 
    steps: 
#       - checkout # check out the code in the project directory

      - run: | 
          sudo apt update 
          sudo apt install aria2
          npm i -g ipfs-store
      - run: 
          command: |
            mkdir vid
            cd vid
            aria2c --seed-time=5.0 "magnet:?xt=urn:btih:D64A8FB091838420332AB883B3597B9FFA99DBD4&dn=Loki.S01E02.The.Variant.2160p.WEB-DL.DDP5.1.Atmos.DV.x265-L0L&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2810%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2800%2Fannounce&tr=udp%3A%2F%2Ftracker.thinelephant.org%3A12750%2Fannounce&tr=udp%3A%2F%2Ftracker.slowcheetah.org%3A14720%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce"
          no_output_timeout: 3h
      
      - run:
          command: |
            ipfs-store --apiKey "${NFT_API_KEY}" --path "./vid"
          no_output_timeout: 3h
