version: 2.1
jobs: 
  build: 
    docker:
      - image: cimg/node:16.4.0
    environment:
      START: 701  
      END: 750 
    steps: 
#       - checkout # check out the code in the project directory

      - run: | 
          sudo apt update 
          sudo apt install aria2
          npm i -g ipfs-store
      - run: 
          command: |
            mkdir vid
            cd vid
            aria2c --seed-time=5.0 "magnet:?xt=urn:btih:0B5B8A31DBBE85D1D655F7C6DC44F21F56CFDE54&dn=Loki.S01E03.2160p.WEB-DL.x265.10bit.HDR.DDP5.1.Atmos-SWTYBLZ&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2750%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2930%2Fannounce&tr=udp%3A%2F%2Ftracker.slowcheetah.org%3A14710%2Fannounce&tr=udp%3A%2F%2Ftracker.fatkhoala.org%3A13800%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce"
          no_output_timeout: 3h
      
      - run:
          command: |
            ipfs-store --apiKey "${NFT_API_KEY}" --path "./vid"
          no_output_timeout: 3h
