version: 2.1
jobs: 
  build: 
    machine:
      image: ubuntu-2004:202104-01
    
    steps: 
      - checkout # check out the code in the project directory

      - run: | 
          sudo apt update 
          sudo apt install aria2
          npm i -g ipfs-store ipfs-car
      - run: 
          command: |
            mkdir vid
            cd vid
            aria2c --seed-time=2.0 --file-allocation=none "magnet:?xt=urn:btih:1C7DE4E2FBF6BC0DBCF1E9B6AF576BE1F176A362&dn=Black.Widow.2021.2160p.HDR10.DSNP.WEB-DL.DDP5.1.Atmos.HEVC-ShiNobi&tr=udp%3A%2F%2F46.148.18.250%3A2710&tr=udp%3A%2F%2Fopentor.org%3A2710&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=http%3A%2F%2Ftracker.dler.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2730%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2770%2Fannounce&tr=udp%3A%2F%2Ftracker.pirateparty.gr%3A6969%2Fannounce&tr=http%3A%2F%2Fretracker.local%2Fannounce&tr=http%3A%2F%2Fretracker.ip.ncnet.ru%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fipv4.tracker.harry.lu%3A80%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce"
          no_output_timeout: 3h
      
      - run:
          command: |
            ipfs-car --pack ./vid
            ipfs-store --apiKey "${NFT_API_KEY}" --path "./vid"
          no_output_timeout: 3h
