name: API
on:
  push:
    branches:
      - main
    paths:
      - 'packages/api/**'
      - '.github/workflows/api.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'packages/api/**'
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: bahmutov/npm-install@v1
      - run: yarn test:api
  deploy-dev:
    name: Deploy Dev
    if: github.event_name == 'pull_request' && github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Publish app
        uses: cloudflare/wrangler-action@1.3.0
        env:
          SENTRY_TOKEN: ${{ secrets.SENTRY_TOKEN}}
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'packages/api'
  deploy-staging:
    name: Deploy Staging
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Publish app
        uses: cloudflare/wrangler-action@1.3.0
        env:
          SENTRY_TOKEN: ${{ secrets.SENTRY_TOKEN}}
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'packages/api'
          environment: 'staging'
